### PR TITLE
Fix tab-closing bug and other updates.

### LINKED ISSUE #50: crashed the application
Followed installation guidelines (revised per PR #49) on RHEL7 x86_64.

1. Application started and presented runs from some (demo?) databroker.  Good.
1. Lots of console traceback output as I moved mouse over the window.
1. Double clicked on ScanID 1
1. Tab opened in right-side panel: shows Header, Baseline, ...
1. Visual inspection of document content (in the different tabs) looks fine.
1. Crashed the application when I clicked the [x] box on the run's tab in right side panel.

This report on the console:

```
Traceback (most recent call last):
  File "/home/oxygen18/JEMIAN/sandbox/bluesky-browser/bluesky_browser/viewer/viewer.py", line 207, in close_tab
    self.parent().close_run_viewer(widget)
AttributeError: 'QSplitter' object has no attribute 'close_run_viewer'
Aborted
```

Very reproducible.

### PR DESCRIPTION
**Pull request by danielballan**
See commit messages for details.

Closes #50

### CODE REVIEW

**Review by prjemian — COMMENTED** [review]
I confirm changeset 6452ebc resolves the problem reported in #50.  

This PR also includes changes that do not display any graphics (line chart or mesh chart).  Is that temporary?  Since this repo is a WIP, I approve the PR but hope the visualization will return soon.  I'd love to use this tool satisfy a request at [APS 8-ID-I XPCS](https://github.com/aps-8id-trr/ipython-8idiuser/issues/35).

**Comment by danielballan** [comment]
Do you mean that this PR apparently breaks the plotting / removes the plots? That is definitely not intentional. I can't reproduce that problem myself. Here some screenshots from running `bluesky-browser --demo` on commit 970c195a70c094901ddea5be62940f1b1624123d:


image

image

**Review by mrakitin — APPROVED** [review]
Looks good to me.

**Comment by prjemian** [comment]
When I reported previously, there was no *Scalers v. time* tab.  On launching from a new console, it's there now so no problem for me.  Wonder why that was?  Might try to repeat that with a new environment and install of bluesky-browser.  Is it a first-time-only issue or random occurrence?

Merge this and we'll keep on the lookout for this situation.

+1^100 for unit testing!

**Comment by danielballan** [comment]
Agreed. As I mentioned on the call, I _have_ seen this before so I definitely you believed you observed this, but I don't have a good theory for under what conditions it occurs. Unit tests soon.

**Pull request merged**
